# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:mac)

xcodes(version: "16.3")

desc "Description of what the lane does"
lane :build do |options|
	gym(
		scheme: "muti",
		output_directory: "artifacts",
		configuration: "Debug",
		skip_package_ipa: true,
		skip_codesigning: true,
		export_method: "development",
		skip_package_pkg: true
	)
end