name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    name: Main
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
      
      - name: Build
        run: bundle exec fastlane build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          path: artifacts/